### ISSUE TITLE
Escaped characters bug *verified

### ISSUE THREAD

**Issue by maxiedaniels** [guilhermesad/rspotify#101]
**EDIT**

In *connection.rb*, URI::encode is used at line 59. However, URI::encode does not encode `[` and `]`, and is deprecated. Switching this to use the Addressable gem's `Addressable::URI.parse(url).normalize.to_s` fixes the issue, and prevents double encoding from occuring.

The user then has to use `ERB::Util.url_encode()` to encode parameters going into RSpotify methods.

**Original Post**

I'm running into a strange issue, specifically the Playlist search (using `RSpotify::Playlist.find()`). I'm providing a playlist ID and the owner's ID, but in some cases the owner's username has characters that require escaping.

This user for example: https://open.spotify.com/user/andy%3F%21

Their username is `andy?!`, which, when escaped, turns to `andy%3F%21`. However, when I try and retrieve one his playlists using the Playlist search, I'm getting a 404 error, `Invalid username`. I've triple checked, and I'm definitely providing the escaped character version of the username (using `CGI.escape`).

I also tried going to the Spotify Web API Console and `andy%3F%21` works correctly there. Is this some bug with the RSpotify gem?

**Comment by guilhermesad** [comment]
Closed by #181.
