### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by nstares0** [guilhermesad/rspotify#115]
Hi,

When my callback returns, I see in the log that `Processing by UsersController#spotify` has occurred. However, none of the code in the spotify method (including a print statement) executes. 
The log reports `Completed 401 Unauthorized`. I should note that I am never redirected to the spotify site to log in. 

Any suggestions much appreciated.

**Comment by artjomjuferov** [comment]
For me it started to happen on the 29th of May. I don't use any authentication and have not before. Now anytime I try to call basic method for instance `RSpotify::Track.search "John" ` it fails with `NoMethodError: undefined method `empty?' for nil:NilClass`. I know that Spotify has started to require auth token.

**Comment by estebanutz** [comment]
@nstares0 and @artjomjuferov check out the documentation and make sure add authentication. 
`RSpotify.authenticate("<your_client_id>", "<your_client_secret>")`

You'll need to create an app in spotify to get the credentials here: https://developer.spotify.com/my-applications

I added that to our app and it fixed the "empty?" error which we were getting as well. I hope that helps.

**Comment by artjomjuferov** [comment]
@estebanutz thanks. After I had started receive such errors I added authentication. And it works 99 from 100 times. I receive `RestClient::Unauthorized: 401 Unauthorized`.

**Comment by estebanutz** [comment]
@artjomjuferov We haven't had any issues with our app so far. I'll let you know if we do.

**Comment by aldosolorzano** [comment]
I'm having the same issue even with the authentication, I regenerated the token a few times to see if that was the problem but It didn't work. @artjomjuferov let me know what the Spotify support said.

**Comment by zessx** [comment]
Same there, but only if I use rspotify with RoR.  
A standalone script works well, and if I copy the exact same code in a RoR controller, it will always trigger a 401.

**Comment by rmeritz** [comment]
@zessx - I had the same problem you did where it worked without RoR but broke without RoR but I was able to fix it by installing the gem via the bleeding edge on github instead of what is packaged in the gem which is quite old.

**Comment by aldosolorzano** [comment]
@rmeritz  Thanks, this fixed my problem :)

**Comment by sdkevorkian** [comment]
@rmeritz  and @aldosolorzano  I am having the 401 search issue in ruby on rails with the simple artists, tracks, albums search on the ReadMe. 

But, I am pretty new to web dev... What do you mean by install the gem via bleeding edge on github?

**Comment by aldosolorzano** [comment]
@sdkevorkian 
change gem 'rspotify' 
to gem 'rspotify', git: 'https://github.com/guilhermesad/rspotify.git' in your GemFile.
Hope it helps

**Comment by sdkevorkian** [comment]
I had to update ruby and do some other things but I did get it to work! thank you!!

**Comment by paulsturgess** [comment]
https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/

**Comment by otmusic** [comment]
Hi, today i get error "KeyError: key not found: :ciphers" when i try call RSpotify::Track.search('Bryan Kearney Te amo')

**Comment by sdkevorkian** [comment]
Hi again,

I am getting a 401 error occasionally on my auth route. it occurs when the user hasn't been to my site in a while, and then the 2nd attempt to log in works fine. is there a way to access the status code after attempting to make a new user? I would like to redirect the user let them know to attempt logging in 1 more time in that case. Unless there is another way I can handle this error.

**Comment by artjomjuferov** [comment]
Hey guys, we eventually made a fix.
https://github.com/guilhermesad/rspotify/pull/121
