### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by Sphinxs** [guilhermesad/rspotify#120]
I need all images url's the user searched, I can go through the *Album* and get the release date, available markets of all Albums available, but I can't do the download of the images, tips ? ( I think to do the download this way [here](https://stackoverflow.com/questions/6768238/download-an-image-from-a-url) )

My code :

```
Root = RSpotify::Artist.search( 'Gorillaz' ) # User.to_s

Arti = Root.first

Albm = Arti.albums

...

count = 1

while Albm do # With .each don't run, I don't know why ( :
    
    print "\n#{Albm [count].name}\n\n"

    count += 1

end

```

Extra : What's returned in `Albm[2].images` for example ?

**Comment by ORoberts221** [comment]
The Album.images method returns an array of hashed items, as you can see in the full documentation [here ](http://www.rubydoc.info/github/guilhermesad/rspotify/master/RSpotify/Album#images-instance_method)

So you need to access the url for the images, I used this method:
```ruby
def get_album_art(current_track)
    album_art = current_track.album.images.first
    return album_art['url'];
end
