### ISSUE TITLE
Authorisation Token not automatically refreshing

### ISSUE THREAD

**Issue by ORoberts221** [guilhermesad/rspotify#148]
Apologies if I'm doing something wrong here, but I have my application working perfectly except after an hour or so the API requests fail and return a 404 error with the message `Invalid username`, this appears to originate from the send_request method. Full error message is below. 

Is there something else I should be doing that I'm not currently?

![image](https://user-images.githubusercontent.com/10622911/33208161-6462517a-d108-11e7-9556-1819b00cdf43.png)

**Comment by jefrice** [comment]
I am seeing this issue now too. I know it is marked as fixed - but it is not fixed for me. I am using gem 'rspotify', '2.1.0'

**Comment by iamkristian** [comment]
I do too - using the same version

**Comment by guilhermesad** [comment]
Fixed by #165. Please use `2.1.1` version. LMK if you face any more issues on this.
