### ISSUE TITLE
Error when requesting User's followed artists (RestClient::BadRequest: 400 Bad Request)

### ISSUE THREAD

**Issue by dahveed-rb** [guilhermesad/rspotify#150]
```
irb>> hash = User.first.spot_hash
irb>> spotify_user = RSpotify::User.new(hash)
irb>> spotify_user.following(type: 'artist')
RestClient::BadRequest: 400 Bad Request
```

I'm persisting the user hash into a table. When I try to get the artists that the user is following I get a 400 Bad Request error. I noticed that when I make the request in the console it makes three consecutive requests and returns the error. Has anyone else had this problem or found a way to work around this?

**Comment by dahveed-rb** [comment]
The cause of the error was due to the fact that I hadn't restarted my server when I updated the scope in omniauth.rb to include user-follow-modify and user-follow-read...

**Comment by jessmartin** [comment]
@dahveed-rb I ran into this same issue. Looks like you resolved it. Care to post your resolution?
