### ISSUE TITLE
Issue authenticating spotify user

### ISSUE THREAD

**Issue by jefrice** [guilhermesad/rspotify#162]
I am using the code given in the examples -- and prior to (recently?) it worked. TBH, I don't know when it stopped working bc I haven't tested it in at least a month. But now when I click the link for authenticating via spotify i get: 

undefined method `[]' for nil:NilClass

I have this:
```
# config/application.rb
RSpotify::authenticate("<your_client_id>", "<your_client_secret>")
```
```
require 'rspotify/oauth'

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :spotify, "<your_client_id>", "<your_client_secret>", scope: 'user-read-email playlist-modify-public user-library-read user-library-modify'
end
```
`<%= link_to 'Sign in with Spotify', '/auth/spotify' %>`

```
# config/routes.rb

get '/auth/spotify/callback', to: 'users#spotify'
```

As well as the right client/secret from my spotify app. In fact, the rest of the API works fine, i.e. searching for artists, albums, tracks, etc. This one call won't work.

Any ideas?

**Comment by jefrice** [comment]
Actually - in your documentation it says:

<%= link_to 'Sign in with Spotify', '/auth/spotify' %>
And create a route to receive the callback:

# config/routes.rb

get '/auth/spotify/callback', to: 'users#spotify'

but if you don't add a route for /auth/spotify - it generates a route not found error.

Isn't this supposed to generate a popup so the user can login to their spotify? bc that isn't happening either way. 

what am i missing?

**Comment by jefrice** [comment]
I should also mention that I am using devise for authentication in my application - and the spotify oauth is meant for accessing spotify only - not authenticating my main application (at this point).

**Comment by jefrice** [comment]
I figured it all out - it was some oauth/devise configuration issues. I do with this repo was better maintained tho -- no communication whatsoever. bummer.

**Comment by guilhermesad** [comment]
Hi @jefrice, I started debugging your issue but hadn't have the time to dive deep into it, that's why I hadn't reply yet. Glad you sorted it out, cheers.

**Comment by jefrice** [comment]
Ah - ok. I appreciate it. I am having an issue with expiring tokens now... I get a 403 forbidden after 60 minutes. Any ideas?
