### ISSUE TITLE
InvalidURIError when square brackets in URI

### ISSUE THREAD

**Issue by Ryan-Berry** [guilhermesad/rspotify#164]
For example, when calling this URL: 

https://api.spotify.com/v1/users/pie[]overlord/playlists/5azo5iYFJeptUjiTQ6DGoL

I get the URI::InvalidURIError: bad URI(is not URI?) error.

It doesn't appear that `url = URI::encode(url)` in connection.rb is handling these. 

I've looked into a fix for this but what I found is suggesting using Addressable as an alternative to URI, so `Addressable::URI.encode(url)`

Ref: https://github.com/rest-client/rest-client/issues/476

**Comment by Deuteu** [comment]
More over it seems recommended to avoid using `URI.encode`
https://rubocop.readthedocs.io/en/latest/cops_lint/#linturiescapeunescape

**Comment by guilhermesad** [comment]
Closed by #181.
