### ISSUE TITLE
Playlist endpoints will change on Sept. 11th 2018

### ISSUE THREAD

**Issue by jbwl** [guilhermesad/rspotify#167]
Hi, I just found out that Spotify will change the Playlist endpoints because it will not longer allow the user part of an URI:

https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

I'd be happy to see this great gem get updated in time!

Thank you

**Comment by guilhermesad** [comment]
Hi @jbwl! Please note on that page:
> the old URLs will continue to function until further notice.

Moreover, seems we're not relying on this structure in any place, so we should be good. Thanks!

**Comment by carlosefonseca** [comment]
Hi! I'm having troubles removing tracks from playlists (Spotify returns 403 Forbidden) and I think this is the cause. I removed the user part on the URL and the request succeeded. I'll open a PR with a change to the Playlist @path.
