### ISSUE TITLE
Need help with authentication

### ISSUE THREAD

**Issue by emperorliu** [guilhermesad/rspotify#39]
Hi,

I'm following the ReadMe, and I'm a little bit confused about where it says

<%= link_to 'Sign in with Spotify', '/auth/spotify' %>

And then after that, there's the link to the /auth/spotify/callback in routes.rb. I'm a little confused how I'm supposed to get the /auth/spotify button to click to the authentication page, since it doesn't build a route for it. I followed all the steps under Rails + Oath. Sorry for the noobie question... I'm still learning, just trying to create a simple app.

**Comment by Belibaste** [comment]
Hi,

Did you find the solution to this problem ? I am stuck here too :-)

**Comment by joshuabamboo** [comment]
@Belibaste @emperorliu -- This is admittedly confusing and I'm sure you've figured it out in the last year, but... :) 

In order for `<%= link_to 'Sign in with Spotify', '/auth/spotify' %>` to work, you must first set the Redirect URI on [your Spotify app page](https://developer.spotify.com/my-applications/#!/applications) to  "<<your site>> /auth/spotify/callback".

**Comment by Belibaste** [comment]
Still many thanks, I did not put the answer here after I found it, my bad, your glory !
