### ISSUE TITLE
Question about retrieving other peoples playlists

### ISSUE THREAD

**Issue by emperorliu** [guilhermesad/rspotify#40]
Hi, 

Here is my gist: https://gist.github.com/emperorliu/178cbb86c660f296b091

When I'm logged in myself, I can retrieve my own playlists, but I can't do it when it's with another user_id, it gives me the error 

>> RSpotify::Playlist.find("seanarturo", "1sPEU0bs81JzaRXpyQWNCm")
!! 400 Bad Request: {
  "error": {
    "status": 400,
    "message": "Only valid bearer authentication supported"
  }
}

This happens for both other users's public and private playlists.. I'm a little confused. I'm logged in with Oath, my omniauth.rb file is as so:

provider :spotify, ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"], scope: 'user-read-email playlist-modify-public playlist-modify-private playlist-read-private user-library-read user-library-modify'

Any help is very much appreciated. Thank You!

**Comment by guilhermesad** [comment]
Hi @emperorliu,

Retrieving other people's playlists requires client authentication, which is different from OAuth. Since you're using Rails, have a look at the [instructions](https://github.com/guilhermesad/rspotify#rails--oauth) for it in README. You'll see that you also have to use `RSpotify::authenticate`, besides using OAuth.

If you're interested in the differences between the two authentication methods have a look at the [Spotify Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/). They have a good explanation about this.

Thanks

**Comment by emperorliu** [comment]
@guilhermesad 

Hmm... but I did include that line in my initializer (spotify.rb)

RSpotify::authenticate(ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"])

I put it in the initializer because putting it in application.rb didn't work for me..

Am I missing something? (sorry)

**Comment by emperorliu** [comment]
@guilhermesad 

It's strange because in the web console for "Get a Playlist".. i copied the my access_token, the playlist_id, and the user_id for the playlist owner to the console and it worked. But when I try to do it by RSpotify::Playlist.find like I did above, I get that bad request error

**Comment by guilhermesad** [comment]
I've tried to reproduce your error in several ways but everything is running ok here. Have you tried the method in the ruby console after loading the gem? (outside Rails). It should work after `RSpotify::authenticate`. This "Only valid bearer authentication supported" message refers exactly to the client authentication. So I guess the problem may lie in your Rails config somewhere, it seems not to be initializing properly.

**Comment by emperorliu** [comment]
@guilhermesad 

I figured it out. I accidentally put spotify.rb in the config directory, but not in the initializer folder within the config directory. Agh!!!! :P Sorry for the trouble. Thank you so much for the help, and your gem is awesome! :)
