### ISSUE TITLE
How can I add tracks to "starred" playlist in Spotify?

### ISSUE THREAD

**Issue by sshinde-systango** [guilhermesad/rspotify#41]
Hi,
By using this gem, I'm able to add tracks in other playlists but not in "starred" playlist. I'm getting 500 Internal server error. Anyone can please let me know how can do this?

I just want to make a track as starred track in spotify, is there any other way using spotify web api to perform this?

Thanks

**Comment by guilhermesad** [comment]
Hi @sshinde-systango. The Spotify API does not support operations on the starred playlist yet, so unfortunately that's not possible. You can only [find a starred playlist](http://www.rubydoc.info/github/guilhermesad/rspotify/master/RSpotify/Playlist.find), but it's not an official endpoint and may be discontinued at any time. Let's hope they'll implement something related in the future.
