### ISSUE TITLE
RSpotify::User.new(request.env['omniauth.auth']) returns incomplete user

### ISSUE THREAD

**Issue by spilth** [guilhermesad/rspotify#43]
It looks like Spotify changed the structure of the data returned during the authorization process.

Several fields have moved from the `info` section to a `extra.raw_info`.  Below is an example:

    {
        'provider' => 'spotify',
        'uid' => 'spilth',
        'info' => {
            'name' => 'Brian Kelly',
            'nickname' => 'spilth', 'email' => 'polymonic@gmail.com',
            'urls' => {'spotify' => 'https://open.spotify.com/user/spilth'},
            'image' => 'foo'
        },
        'credentials' => {
            'token' => 'foo',
            'refresh_token' => 'bar',
            'expires_at' => 1423766850,
            'expires' => true
        },
        'extra' => {
            'raw_info' => {
                'country' => 'US',
                'display_name' => 'Brian Kelly',
                'email' => 'polymonic@gmail.com',
                'external_urls' => {'spotify' => 'https://open.spotify.com/user/spilth'},
                'followers' => {
                    'href' => nil,
                    'total' => 4
                },
                'href' => 'https://api.spotify.com/v1/users/spilth',
                'id' => 'spilth',
                'images' => [
                    {
                        'height' => nil,
                        'url' => 'bar',
                        'width' => nil
                    }
                ],
                'product' => 'premium',
                'type' => 'user',
                'uri' => 'spotify:user:spilth'
            }
        }
    }

Which results in me ending up with the following:

    spotify_user
    => #<RSpotify::User:0x007fa0084c2f70
     @country=nil,
     @display_name=nil,
     @email="polymonic@gmail.com",
     @external_urls=nil,
     @followers=nil,
     @href=nil,
     @id=nil,
     @images=nil,
     @product=nil,
     @type=nil,
     @uri=nil>

**Comment by guilhermesad** [comment]
Spotify API is still returning the data ok (it's possible to check it [here](https://developer.spotify.com/web-api/console/get-current-user/)). It seems to be a problem with the omniauth-oauth2 parser, one of the dependencies.

However I tested it here and I'm getting the data correctly. I saw you forked the repo, did you change `oauth.rb` or are using your own version of the gem? If not, please tell me which versions are shown in your app's Gemfile.lock for `omniauth-oauth2`, `omniauth` and `oauth2` gems.

**Comment by spilth** [comment]
Hi Guilherme,

Thanks for the reply.  I should've thought to check the response with their API console. I was curious why I seemed to be the only person having this issue.  I forked the repo in case it was an issue I could fix - I couldn't find a test for `RSpotify::User.new` so I was going to add one with what I assumed was the new response above.

Here are my Gem versions:

    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      multi_json (~> 1.3)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-spotify (0.0.5)
      omniauth-oauth2 (~> 1.1)

**Comment by spilth** [comment]
Okay, once I pulled out ''omniauth-spotify' things started working again.

**Comment by guilhermesad** [comment]
:+1: Yes, `omniauth-spotify` also uses `omniauth-oauth2` so it was overriding RSpotify's.

**Comment by guilhermesad** [comment]
:+1: Yes, `omniauth-spotify` has its own OAuth config so it was overriding RSpotify's.
