### ISSUE TITLE
Follow Playlist

### ISSUE THREAD

**Issue by Yaroslav-F** [guilhermesad/rspotify#46]
Hi, I am trying to build an app which will allow users to post and follow spotify playlist. 
Users login is implemented through devise like:
config.omniauth :spotify, '<<app_id>>', '<<app_secret>>', :scope => 'playlist-read-private user-follow-modify'
Now I am able to fetch a user and a playlist:

[2] pry(#<StatusesController>)> spotify_user
=> #<RSpotify::User:0x00000003558b80
 @birthdate=nil,
 @country=nil,
 @display_name="Yaroslav Filyk",
 @email=nil,
 @external_urls={"spotify"=>"https://open.spotify.com/user/11178419014"},
 @followers={"href"=>nil, "total"=>1},
 @href="https://api.spotify.com/v1/users/11178419014",
 @id="11178419014",
 @images=
  [{"height"=>nil,
    "url"=>"https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1/v/t1.0-1/1185646_569428653117203_1802750611_n.jpg?oh=d94d6fdfa782b4c73b0faf2cebcdab6b&oe=55AAA2B1&__gda__=1441124271_1c26dec8fe9e8a660a735a8021ade0e3",
    "width"=>nil}],
 @product=nil,
 @type="user",
 @uri="spotify:user:11178419014">

[3] pry(#<StatusesController>)> playlist
=> #<RSpotify::Playlist:0x000000036e2050
 @collaborative=false,
 @description="Futuristic retro in the modern world. Artwork by Kilian Eng.",
 @external_urls={"spotify"=>"http://open.spotify.com/user/wizzler/playlist/6cWcjjZlVb8UGW1ZiMKf3l"},
 @followers={"href"=>nil, "total"=>586},
 ...

The problem is: I can't do anything related to rspotify follow features it gives me this error:

[4] pry(#<StatusesController>)> spotify_user.follows?(playlist)
NameError: uninitialized class variable @@users_credentials in RSpotify::User

Can you help me out with this? Maybe I've picked the wrong scope or smth?

**Comment by guilhermesad** [comment]
How are you initializing `spotify_user`? Also, in `config.omniauth :spotify, '<>', '<>', :scope => 'playlist-read-private user-follow-modify'` you're putting your credentials inside the brackets right?

**Comment by Yaroslav-F** [comment]
instead of brackets, right :)
as for `spotify_user` : 
`RSpotify.authenticate("credential", "credential")`
`spotify_user = RSpotify::User.find(current_user.spotify_uid)`
`playlist = RSpotify::Playlist.find(other_user.spotify_uid, playlist_spotify_id)`
`spotify_user.follow(playlist)` - throws an error described above

**Comment by guilhermesad** [comment]
So you're using `User.find` to get `spotify_user`, but what you should use in this case is `User.new` passing in the authorization that comes in the request you'll receive from Spotify. Please have a read [here](https://github.com/guilhermesad/rspotify#rails--oauth) for the steps to take.

**Comment by Yaroslav-F** [comment]
Yes, works now, thanks man!
