### ISSUE TITLE
RSpotify doesn't authenticate all requests

### ISSUE THREAD

**Issue by MentalPower** [guilhermesad/rspotify#48]
Hi,

It seems that RSpotify doesn't authenticate all requests. This leads to lower rate limits being applied to read-only API requests such as RSpotify::Track.search(). Can we change this behaviour when RSpotify.authenticate has already been called? Specifically, https://github.com/guilhermesad/rspotify/blob/master/lib/rspotify/base.rb#L97 is calling the bare `get` instead of `auth_get`.

https://developer.spotify.com/web-api/user-guide/#rate-limiting

Thanks!

**Comment by guilhermesad** [comment]
Hi @MentalPower, that's a good call, I hadn't noticed that rate limit. I'll push a commit for this soon, thanks!
