### ISSUE TITLE
Can't initialize a user from OmniAuth

### ISSUE THREAD

**Issue by mikesten** [guilhermesad/rspotify#49]
Following the docs, I tried this:

`spotify_user = RSpotify::User.new(request.env['omniauth.auth'])`

Which failed with a `404 resource not found` from RestClient as soon as I tried to fetch the user's playlists. Turning on RestClient debugging I found the following

`RestClient.get "https://api.spotify.com/v1/users//playlists?limit=50&offset=0"`

Note the missing username... Looking at the source for `User` it looks like OmniAuth's `info` hash is being used (https://github.com/guilhermesad/rspotify/blob/master/lib/rspotify/user.rb#L71). This gets passed into the constructor for `Base`, which looks for an `id` key. There isn't one returned from OmniAuth (keys present are `email`, `image`, `name`, `nickname`, `urls`) so all subsequent calls will fail.

I've monkey patched this in my code as follows:

```
auth_hash = request.env['omniauth.auth']
auth_hash["info"].merge!({ "id" => auth_hash["uid"] })
spotify_user = RSpotify::User.new(auth_hash)
```

Would you like me to submit a pull request with this fix rolled into `User` or do you have any ideas for a more elegant solution?

**Comment by guilhermesad** [comment]
Hi @mikesten, sorry for taking so long. So, I've tried that locally and I get the following for `request.env['omniauth.auth']`:
```ruby
{"provider"=>"spotify",
 "uid"=>nil,
 "info"=>
  {"birthdate"=>"1991-09-26",
   "country"=>"BR",
   "display_name"=>"Guilherme Sad",
   "email"=>"gorgulhoguilherme@gmail.com",
   "external_urls"=>{"spotify"=>"https://open.spotify.com/user/guilhermesad"},
   "followers"=>{"href"=>nil, "total"=>33},
   "href"=>"https://api.spotify.com/v1/users/guilhermesad",
   "id"=>"guilhermesad",
   ...
```
Notice that `id` is there inside `info`, and `uid` equals `nil`. Have you put `require 'rspotify/oauth'` in `config/initializers/omniauth.rb`?

**Comment by mikesten** [comment]
No worries, @guilhermesad!

Ah, no. I'm not using Rails so I skipped the `Rails + OAuth` section. I'm using `omniauth-spotify` directly and passing `request.env['omniauth.auth']` from there - that'll be the problem... Thanks. :+1:

**Comment by guilhermesad** [comment]
I see. Yeah, both `rspotify` and `omniauth-spotify` depend on the same gem, `omniauth-oauth2`, but use it differently. So you could either follow the `rspotify` way, explained on "Rails + OAuth" section, or tweak the hash returned from `omniauth-spotify` to look like the one `rspotify` is expecting, like you did. Thanks.
