### ISSUE TITLE
Encode error

### ISSUE THREAD

**Issue by loginerrort** [guilhermesad/rspotify#52]
when i search or find a artist, if the artist with Chinese name it may cause errors.
ex:
```ruby
require 'rspotify'

arctic_monkeys = RSpotify::Artist.find('2elBjNSdBE2Y3f0j1mjrql')
puts arctic_monkeys.name
arctic_monkeys.related_artists.each do |i|
	puts i.name
end
```

output
```
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE5" followed by "\x91"
 on CP950 (Encoding::InvalidByteSequenceError)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `new'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `parse'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspotify-1.14.0/lib/rspotify/conne
ction.rb:56:in `send_request'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspotify-1.14.0/lib/rspotify/conne
ction.rb:35:in `block (2 levels) in singleton class'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspotify-1.14.0/lib/rspotify/base.
rb:51:in `find_one'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspotify-1.14.0/lib/rspotify/base.
rb:36:in `find'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspotify-1.14.0/lib/rspotify/artis
t.rb:25:in `find'
        from test.rb:3:in `<main>'
```

how to deal with it?

Nice work this API!!

**Comment by guilhermesad** [comment]
Hi @loginerrort, this is the output I get for your snippet:
```
王力宏
陶喆
蔡依林
五月天
潘瑋柏
光良
楊丞琳
. . . 
```
Works ok for me. I've tried it on ruby 2.1.0 as well, which seems to be the version you're using. Have you tried to update the gem or the ruby version itself?

**Comment by loginerrort** [comment]
@guilhermesad 
My gem version is 2.2.3 .
Ruby as u see is 2.1.5

maybe my platform is windows?
what's your os?
thank you

**Comment by guilhermesad** [comment]
There isn't such version for RSpotify, it's still on `1.15.0`. I can see you're using `1.14.0`. And the ruby version I see is `2.1.0`. Anyway, those shouldn't interfere, and neither the os...

The problem seems to happen when the `json` gem used by your ruby version tries to parse the response RSpotify receives. So I'd try to update it or your ruby version itself to see if it solves before moving to something else.

**Comment by loginerrort** [comment]
I have tried ruby 2.1.0 & 2.1.5 but all meet the same problem.
Hope u can fix it~
Thanks.

**Comment by guilhermesad** [comment]
As explained this should be a problem with your ruby dependencies, doesn't have to do with this gem. If you try to parse Chinese in JSON outside RSpotify you'll probably get the same error. So unfortunately there's not much else I can do. I'd recommend you to try to reinstall or update your ruby version to `>= 2.2.0`. Thanks.

**Comment by loginerrort** [comment]
Thank you for ur responding.
I have solve this problem.
I have tried the same code with Ruby 2.2.2 and Windows 8.1 , but still not work well.
But I try on Ubuntu and Ruby, it run perfect.
