### ISSUE TITLE
Encoding nested objects to json

### ISSUE THREAD

**Issue by s** [guilhermesad/rspotify#55]
Hi,

Recently trying to get nested objects encoded to json in <code>Rails</code>. I am searching a query like this:
<code>results = RSpotify::Album.search(q, limit:5)</code>
And then trying to return to the front-end in json format:
<code>render json: results</code>
The problem is that I get an array of albums which have <code>Artists</code> object in them. And these <code>Artists</code> become <code>null</code> in json when I encode. Is there a way to encode this nested objects? 
Actually if there would be a method to return raw json from Spotify's original response, it'd be awesome.

Thanks,
/Said

**Comment by s** [comment]
The reason I'm encoding whole <code>Album</code> object is that if I iterate over the results and extract valuable values for my purpose, response time of the rails route increases dramatically and makes it slower.

**Comment by guilhermesad** [comment]
Hi @s, thanks for raising this concern. I've been willing to add that option for some time, finally got the time to code it. The commit above introduces a way to get the raw response from any request. Have a look in [here](https://github.com/guilhermesad/rspotify#getting-raw-response) for its usage. Thanks.
