### ISSUE TITLE
raw_response Error

### ISSUE THREAD

**Issue by KirioXX** [guilhermesad/rspotify#57]
I try to get the raw response but I get the Error 'undefined method 'raw_response=' for RSpotify:Modul'.

Is there a way to fix this?

**Comment by guilhermesad** [comment]
@KirioXX can you give more details of how you're getting to that? Which commands did you run?

**Comment by KirioXX** [comment]
@guilhermesad  I try to use it in my Volt app as a Task it looks like this and 

````ruby
require 'rspotify'

class SpotifyTask < Volt::Task

    def search(term)
        RSpotify.raw_response = true
        results = RSpotify::Base.search(term, 'artist, album, track')
        RSpotify.raw_response = fales
        return results
    end

end
````

and in the controller I call the Task like this:

````ruby
SpotifyTask.search('Test').then do |results|
    puts results
end.fail do |err|
    puts err
end
````

I add it all so to the gemfile

**Comment by guilhermesad** [comment]
This is a recent feature, so if you were not downloading the gem directly from `git://github.com/guilhermesad/rspotify#master` it wouldn't work.

I just released a new version (1.15.1) with that included, so if you just update your gem it should work now.

**Comment by KirioXX** [comment]
Thank you, with the version 1.15.1 it works.

**Comment by guilhermesad** [comment]
np :+1:
