### ISSUE TITLE
Api-calls not URL-safe

### ISSUE THREAD

**Issue by bobloos93** [guilhermesad/rspotify#58]
Hi there,

First of all, great gem! Over a year time a lot of issues have been solved and a works like a charm right now. 

I may have found one possible issue. If I want to make a playlist for a user with an username with non-url-safe characters, the api calls will break. 

From the Rollbar-log:
bad URI(is not URI?): https://api.spotify.com/v1/users/tést_user/ (real username has been replaced by tést_user). I assume that this call tries to retrieve the playlists of the user.

**Comment by guilhermesad** [comment]
Hi @bobloos93, good catch, thanks. Seems RestClient is not encoding urls in the background, which means we manually have to do it. I'll push a fix for this, thanks for raising the issue.
