### ISSUE TITLE
1.15.2 breaks some search functionality?

### ISSUE THREAD

**Issue by mijit** [guilhermesad/rspotify#62]
In 1.14.0, I could search with a query specifying artist, track, album, etc:

    RSpotify::Track.search("artist:who track:who are you")

But this returns nil in 1.15.2. Is this broken or do I need to do something different?

**Comment by guilhermesad** [comment]
Thanks for flagging this, just fixed it. Please download `1.15.3` for the fixed functionality.

**Comment by mijit** [comment]
Confirmed good, thanks!
