### ISSUE TITLE
Playlists: bad URI(is not URI?) on accented characters

### ISSUE THREAD

**Issue by EssentialMusic** [guilhermesad/rspotify#66]
Hi, 

Finding your Gem really useful, but am having issues polling for data on playlists where the user_id contains accents etc.

For example; https://api.spotify.com/v1/users/spotifyenespañol/playlists/02mIh5SWa1vGk9P93c8zGb produces the error: bad URI(is not URI?): https://api.spotify.com/v1/users/spotifyenespañol/playlists/02mIh5SWa1vGk9P93c8zGb

I've tried to encode the user_id but it's still failing. Without digging into the Gem's source, i'm not sure how to get around it. Have you encountered this problem before?

Many thanks in advance.
Ryan

**Comment by guilhermesad** [comment]
Thanks for flagging this @EssentialMusic, just pushed a fix for it. Please update your gem to `1.15.4`.

**Comment by EssentialMusic** [comment]
Excellent, i'll give that a go now. Thanks!
