### ISSUE TITLE
Omniauth is misbehaving

### ISSUE THREAD

**Issue by morgz** [guilhermesad/rspotify#68]
The latest version of omniauth breaks the oath in this gem.

See this SO question:
http://stackoverflow.com/questions/29543094/issue-with-oauth-in-rails-4-using-spotify/33564639#33564639

I've fixed in my fork by keeping the omniauth gem to 1.3.1
See commit: https://github.com/morgz/rspotify/commit/969d208770e407526c03edea81c3c686e9b79705

**Comment by azisaka** [comment]
:+1: 

we had this issue today during Rails Rumble, thanks to @morgz we had the right fix :)

**Comment by guilhermesad** [comment]
Cherry-picked your commit in 677ae1d04fccb606d50b76ae24c56bf8e6e9662c. Thanks!
