### ISSUE TITLE
displaying more than 20 albums

### ISSUE THREAD

**Issue by solowt** [guilhermesad/rspotify#69]
When I have an artist selected and I call .albums on him/her, it returns a maximum of 20 albums.

Any way to adjust this?

Thanks in advance.

**Comment by guilhermesad** [comment]
@solowt you can set the `limit` in the method call. Please have a look in [here](http://www.rubydoc.info/github/guilhermesad/rspotify/master/RSpotify/Artist#albums-instance_method).
