### ISSUE TITLE
Error when recovering spotify user

### ISSUE THREAD

**Issue by TheDG** [guilhermesad/rspotify#71]
Hello, 
Im working with Rails.
I just could not find the error in my code when authentication with spotify. The following code works:
``` ruby
def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    hash = spotify_user.to_hash
    @a = current_user
    @a.spotify = hash
    @a.save
    puts spotify_user.saved_tracks.size
    redirect_to root_url
end
```

But when trying to run the following code that recovers a spotify user

```ruby
def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    hash = spotify_user.to_hash
    @a = current_user
    @a.spotify = hash
    @a.save
    spotify_user2 = RSpotify::User.new(current_user.spotify)
    puts spotify_user2.saved_tracks.size     
    redirect_to root_url
end
```

crashes on  puts spotify_user2.saved_tracks.size     

with the following error

RestClient::Unauthorized in UsersController#spotify
401 Unauthorized

Any help is greatly appreciated

**Comment by elfenars** [comment]
Did you place the `app_id` and `app_key` in the `application.rb` ?

Also, you can use three backticks ( ` ) to do code blocks.

**Comment by TheDG** [comment]
Thanks for the tip.
I do have the ```RSpotify::authenticate(client_id, client_secret)``` inside application.rb

**Comment by elfenars** [comment]
Also:

```ruby
1 spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
2   hash = spotify_user.to_hash
3    @a = current_user
4    @a.spotify = hash
5    @a.save
6    spotify_user2 = RSpotify::User.new(current_user.spotify)
7    puts spotify_user2.saved_tracks.size     
8    redirect_to root_url
9 end
```

In line 6, shouldn't you be doing `RSpotify::User.new(@a.spotify)`?
I don't know your implementation of `current_user`but it can be that at that point `current_user`token is already expired, but the one you saved in `@a` has the most recent token 

I'm guessing that `@a`is an instance of the User model, if so... you should call the variable `@user` to be more verbose.

**Comment by TheDG** [comment]
Thanks for the tip.
I do have the ```RSpotify::authenticate(client_id, client_secret)``` inside application.rb.
Currently im doing something like this to temporarily fix the problem.
```ruby 
def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    hash = spotify_user.to_hash
    session[:hash]=hash
    spotify_user2 = RSpotify::User.new(session[:hash])
    puts spotify_user2.saved_tracks.size     
    redirect_to root_url
end
´´´
which is not perfect since it requires authenticating with each login.

**Comment by elfenars** [comment]
I noticed that

```
1 spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
2   hash = spotify_user.to_hash
3    @a = current_user
4    @a.spotify = hash
5    @a.save
6    spotify_user2 = RSpotify::User.new(current_user.spotify)
7    puts spotify_user2.saved_tracks.size     
8    redirect_to root_url
9 end
```
In line 6, shouldn't you be doing `RSpotify::User.new(@a.spotify)`?
I don't know your implementation of `current_user` but it can be that at that point `current_user` token is already expired, but the one you saved in `@a` has the most recent token

I'm guessing that `@a` is an instance of the User model, if so... you should call the variable `@user` to be more verbose.

**Comment by TheDG** [comment]
My current_user method is the following
```ruby
def current_user
      return @current_user if defined? @current_user
      @current_user = User.find(session[:user_id]) if session.key?(:user_id)
    end
```
```
About the tip, you are completely right, ill refer to @a as user1 from now on.
The idea is that current_user.spotify is the same as user1.spotify. In my actual code spotify_user2 = RSpotify::User.new(current_user.spotify) would be placed elsewhere so its impossible to call RSpotify::User.new(user1.spotify)
```

**Comment by guilhermesad** [comment]
@TheDG not sure how your `.=` method in `@a` is implemented but it could be that it doesn't reference the same object as `current_user`. So basically:
```
@a = current_user
@a.spotify = hash
```
could be different than
```
current_user.spotify = hash
```
The problem doesn't seem to lie on the hash-to-model conversion regardless (I also tested your scenarios and they're working properly for me)
