### ISSUE TITLE
Why am I getting this error? 400 bad request?

### ISSUE THREAD

**Issue by gmaijoe** [guilhermesad/rspotify#74]
Gavins-MBP:crowdtune gmaister$  rails s
/Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 400 Bad Request (RestClient::BadRequest)
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /Users/gmaister/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/rspotify-1.16.0/lib/rspotify/connection.rb:28:in `authenticate'
	from /Users/gmaister/Desktop/crowdtune/config/application.rb:12:in `<class:Application>'
	from /Users/gmaister/Desktop/crowdtune/config/application.rb:10:in `<module:Crowdtune>'
	from /Users/gmaister/Desktop/crowdtune/config/application.rb:9:in `<top (required)>'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/gmaister/Desktop/crowdtune/bin/rails:9:in `require'
	from /Users/gmaister/Desktop/crowdtune/bin/rails:9:in `<top (required)>'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/lib/spring/client/command.rb:7:in `call'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/lib/spring/client.rb:28:in `run'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/bin/spring:51:in `<top (required)>'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/lib/spring/binstub.rb:11:in `load'
	from /Users/gmaister/.rvm/gems/ruby-2.1.0/gems/spring-1.6.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/gmaister/Desktop/crowdtune/bin/spring:13:in `require'
	from /Users/gmaister/Desktop/crowdtune/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by kepoorhampond** [comment]
Was there any solution to this?

**Comment by Lupeipei** [comment]
Me too. I spend a lot of time to search on Google, but no effective solution
