### ISSUE TITLE
RSpotify::Album should support calls to #total

### ISSUE THREAD

**Issue by brentwalther** [guilhermesad/rspotify#77]
Album should support calls to total so a client can load all the tracks of an album. The current implementation hides this value away. 

An example of an album that has 60 tracks but only 50 are loaded by RSpotify:
`spotify:album:1tNYWgvzsqA4OqNDX9Qhoq`

**Comment by narukami894** [comment]
@guilhermesad @brentwalther 
is this issue solved in #78 ? if so, this issue should be closed 😺

**Comment by guilhermesad** [comment]
@narukami894 it is, thanks.
