### ISSUE TITLE
invalid_grant: Invalid redirect URI {"error":"invalid_grant","error_description":"Invalid redirect URI"}

### ISSUE THREAD

**Issue by logineimer** [guilhermesad/rspotify#80]
Hello,

I tried to connect my Spotify account to my private app on localhost as described [here](
https://github.com/guilhermesad/rspotify#rails--oauth).

After entering my credentials, my app shows me the following error:
`invalid_grant: Invalid redirect URI {"error":"invalid_grant","error_description":"Invalid redirect URI"}`

I read a lot of that error on the internet. However, I wasn't able to fix it myself. Furthermore, I tried it out with several combinations of redirect URLs (e. g. with or without a trailing slash).

What's the problem and how to fix it?

Thanks in advance

**Comment by guilhermesad** [comment]
@logineimer can you paste the code for your "Sign in" link (as in `<%= link_to 'Sign in with Spotify', '/auth/spotify' %>`) and also the contents of your `config/routes.rb`?

**Comment by logineimer** [comment]
@guilhermesad Meanwhile, I've managed to fix the issue on my own. The problem was caused by the omniauth-oauth2 1.4.0 gem which i replaced with 1.3.1.

**Comment by guilhermesad** [comment]
:+1:
