### ISSUE TITLE
New API Functionality

### ISSUE THREAD

**Issue by cameronstanley** [guilhermesad/rspotify#81]
Any plans on implementing the new API functionality? I would be willing to submit a PR if no one else is working on this: https://developer.spotify.com/news-stories/2016/03/29/api-improvements-update/

**Comment by guilhermesad** [comment]
:+1: thanks @cameronstanley, saw those too but haven't had yet the time to implement them. Please go ahead and let me know if you need any help.

**Comment by guilhermesad** [comment]
btw, I'd just ask to add each functionality as a separate PR to make review easier. Thanks!

**Comment by cameronstanley** [comment]
Sounds good, I'll do separate PRs. Thanks!

**Comment by cameronstanley** [comment]
Implemented with #82, #85, and #86.

**Comment by guilhermesad** [comment]
:+1:
