### ISSUE TITLE
wrong number of arguments (2 for 0) in saved_tracks(limit, offset)

### ISSUE THREAD

**Issue by logineimer** [guilhermesad/rspotify#83]
I get a `wrong number of arguments (2 for 0)` error when calling `saved_tracks(limit, offset)` defined in `User`. When calling `saved_tracks` without arguments, there's no problem and I get the first 20 songs from the API.

My code look like this:
`proc { |limit, offset| saved_tracks(limit, offset) }`
...
`yield limit, offset`

When debugging in RubyMine the proc is called with both arguments. Stepping into `saved_tracks(limit, offset)` produces the error. I looked into your source code on my machine (the cached gem) and the arguments are clearly defined in `user.rb`. Maybe it's important to know that I refine the User class to provide a method which supplies all tracks by a user. However, testing the code without the refinement produces the error, too. I proved that by simply calling `spotify_user.saved_tracks(50, 10)` in my controller.

Thanks in advance!

**Comment by logineimer** [comment]
Anybody?

**Comment by guilhermesad** [comment]
@logineimer `limit` and `offset` here are [named arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments), introduced in Ruby 2.0. This means you have to pass them as, for example, `saved_tracks(limit: 10, offset: 20)`. This is so you have more freedom and readability with your optional params. Hope this clarifies it

**Comment by logineimer** [comment]
Yep, that's my fault! Thank you very much.
