### ISSUE TITLE
Getting a RSpotify::User from manual OAuth

### ISSUE THREAD

**Issue by scottopell** [guilhermesad/rspotify#90]
I'm using this in a Sinatra project and I've gotten Spotify OAth working manually (without rails or an oath gem).

I get back valid `access_token`, `token_type`, `expires_in`, `refresh_token`, and `scope` fields from Spotify, however I'm not quite sure how to get a `RSpotify::User` instance from this.

There is a mention in the Readme that one should be able to pass the spotify response into `RSpotify::User#new`, but I haven't been able to get that working. It seems that the constructor for `User` relies on `@id` being populated, which would only happen if there are options passed into the constructor, and that info isn't returned from the OAuth spotify calls.

Is there another call I need to make to the spotify API in order to get the extra information? Or is there something else I'm missing?

Thanks for the great gem btw!

**Comment by scottopell** [comment]
Okay, so I figured this out. Basically you need to make a separate request to the `/me` api endpoint in order to populate the rest of the fields in the initializer.

Basically, after setting up the callback URL, in your callback URL handler, you'll make a request using the stored secret and get your `access_token`, `token_type`, `expires_in`, `refresh_token`, and `scope` fields in the response from the `/api/token` endpoint. Then you'll make a second request to the `/me` endpoint and then you'll combine these two responses and pass that into the constructor.

Here's a code snippet from my project:
```ruby
      # ap auth_response.parsed_response
      #{
      #     "access_token" => "BQD6a8CKJC8YTa...O8J4E3IXeokL98298aI",
      #       "token_type" => "Bearer",
      #       "expires_in" => 3600,
      #    "refresh_token" => "AQA5-xU0OzWc6R...bqWfKAsw6IO4",
      #            "scope" => "user-read-email user-read-private"
      #}
      headers = {
        'Authorization' => "Bearer #{auth_response.parsed_response["access_token"]}"
      }

      info_response = HTTParty.get 'https://api.spotify.com/v1/me',
        headers: headers

      options = {
        'credentials' => auth_response.parsed_response,
        'info' => info_response.parsed_response
      }
      user = RSpotify::User.new options
```

And then you'll have an RSpotify::User and you can store it using the `to_hash` or whatever.

The rest of my project is here if you want a full example:
https://github.com/scottopell/hypem-to-spotify/blob/f314fb0/server.rb#L36

**Comment by DaveSanders** [comment]
I stumbled into this, because we don't use omniauth... it would be really nice if there was a method for handling this directly in RSpotify.  Something to wrapper this up so that I can simply get the user's refreshed token and a fully filled user with the latest spotify info.

Basically, I should be able to initialize a RSpotify::User with just the hash access token and it should do the above.

In the meantime, I'll manage it manually, but something to think about.

**Comment by glenlindquist** [comment]
In the RSpotify::User credentials hash, the access token needs to use the key 'token' rather than 'access_token' in order to successfully make requests. It took me entirely too long to figure this out.
