### ISSUE TITLE
method_missing and respond_to? are broken

### ISSUE THREAD

**Issue by Fryie** [guilhermesad/rspotify#95]
`RSpotify::User.new.blank?`
`NameError: '@empty?' is not allowed as an instance variable name`

The problem is due to this code:
https://github.com/guilhermesad/rspotify/blob/master/lib/rspotify/base.rb#L202
(And the same problem also happens here: https://github.com/guilhermesad/rspotify/blob/master/lib/rspotify/base.rb#L190)

The problem is that methods with a `?` are not valid instance variable names.

**Comment by guilhermesad** [comment]
Fixed! Thanks for flagging this.
