### ISSUE TITLE
/auth/spotify route is not working

### ISSUE THREAD

**Issue by ljrzarate** [guilhermesad/rspotify#96]
Hi, Hope you are doing great
I have an issue hopefully you can help me to solve this:
I add this to my omniauth.rb initializer:

```
require 'rspotify/oauth'

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :spotify,
           ENV["spotify_client_id"],
           ENV["spotify_secret_key"],
           scope: 'user-read-email user-read-private playlist-modify-public user-library-read user-library-modify streaming',
end

```

but then when I try to use the route `/auth/spotify` I'm getting always a 404. Do i need to do something else somewhere?

I'm using Rails 5 and Ruby 2.3.0

Thanks!

**Comment by terryworona** [comment]
@ljrzarate did you ever get this to work? I'm running into the same issue /w Rails 5. Any insight would be appreciated!

**Comment by sdkevorkian** [comment]
Hello, just wanted to add that I am having this same issue, also using rails 5 and ruby 2.3.0

**Comment by mattdrewitt** [comment]
Incase anyone runs into this as I did, the version of omniauth used now requires it to be a post request, so either you need to make your link a post
```
<%= link_to 'Sign in with Spotify', '/auth/spotify', method: :post %>
```
or add
```
OmniAuth.config.allowed_request_methods = [:post, :get]
```
to your initializer

**Comment by rachel-carvalho** [comment]
Thanks for the heads up @mattdrewitt! In case anyone else needs it, after this I also needed to add `omniauth-rails_csrf_protection` to validate the CSRF token, which then required me to have to explicitly add `omniauth` to my Gemfile, so that CSRF's railtie worked.
